"""Load the vendored wire contract and assert tool payloads against it.

The contract is a slim distillation of the pfSense REST API OpenAPI spec: for
every writable endpoint (`POST`/`PATCH`), the valid field names, their JSON
types, enum choices, and the fields required on create. It is generated by
``scripts/generate_contract.py`` from a pinned pkg-RESTAPI release and vendored
as ``contract-v2.10.0.json`` so tests need no network.

Why this exists: the upstream framework **silently ignores unknown request
keys** and **strictly type-checks known ones**, so a misnamed or mistyped field
is either a silent no-op (PATCH) or a hard 400 (POST) that no unit test with a
mocked client would ever catch. These helpers turn that invisible failure mode
into a red test.
"""
from __future__ import annotations

import functools
import json
from pathlib import Path
from typing import Any

# Pinned to the pkg-RESTAPI release the compatibility matrix targets.
CONTRACT_VERSION = "v2.10.0"
_CONTRACT_PATH = Path(__file__).parent / f"contract-{CONTRACT_VERSION}.json"

# Structural/relational keys exempt from field + type checking:
#  - `id` is injected by crud_update/crud_delete for PATCH/DELETE targeting.
#  - `parent_id` identifies a child's parent; its wire form is endpoint-specific
#    (an integer array-index for most ManyModels, but the interface name string
#    for e.g. DHCP servers), so it is not a config-field the contract can type.
_CLIENT_INJECTED_KEYS = {"id", "parent_id"}

# Python type -> JSON Schema type name. bool is checked before int on purpose
# (bool is a subclass of int in Python).
_JSON_TYPE = [
    (bool, "boolean"),
    (int, "integer"),
    (float, "number"),
    (str, "string"),
    (list, "array"),
    (dict, "object"),
]


def _json_type(value: Any) -> str | None:
    for py_type, name in _JSON_TYPE:
        if isinstance(value, py_type):
            return name
    return None


@functools.lru_cache(maxsize=1)
def load_contract() -> dict:
    with open(_CONTRACT_PATH) as fh:
        return json.load(fh)["endpoints"]


def endpoint_key(method: str, endpoint: str) -> str:
    """Build the contract key from the path a tool passes to the client.

    Tools call e.g. ``crud_create("/vpn/openvpn/server", ...)``; the client
    prefixes ``/api/v2``. Contract keys are ``"POST /api/v2/vpn/openvpn/server"``.
    """
    path = endpoint if endpoint.startswith("/api/v2") else f"/api/v2{endpoint}"
    return f"{method.upper()} {path}"


def contract_for(method: str, endpoint: str) -> dict:
    key = endpoint_key(method, endpoint)
    contract = load_contract()
    if key not in contract:
        raise AssertionError(
            f"No contract entry for {key!r}. Either the endpoint path is wrong "
            f"or the contract needs regenerating (scripts/generate_contract.py)."
        )
    return contract[key]


def _type_matches(value: Any, spec: dict) -> bool:
    expected = spec.get("type")
    if expected is None:  # unknown/composite upstream type — don't over-constrain
        return True
    actual = _json_type(value)
    # pfSense PortField etc. are string-typed but tools may pass ints for
    # ergonomics only if they coerce before sending; here we validate the wire
    # value, so an int against a string field is a real mismatch.
    if expected == "number" and actual == "integer":
        return True  # an int is a valid JSON number
    return actual == expected


def check_payload(method: str, endpoint: str, payload: dict) -> list[str]:
    """Return a list of contract violations for a write payload (empty = clean)."""
    spec = contract_for(method, endpoint)
    props = spec["properties"]
    violations: list[str] = []
    for key, value in payload.items():
        if key in _CLIENT_INJECTED_KEYS:
            continue
        if key not in props:
            violations.append(f"unknown field {key!r} (silently dropped by pfSense)")
            continue
        field = props[key]
        if value is None:
            continue
        if not _type_matches(value, field):
            violations.append(
                f"field {key!r} sent as {_json_type(value)}, "
                f"contract requires {field.get('type')}"
            )
            continue
        enum = field.get("enum")
        if enum is not None and not isinstance(value, list) and value not in enum:
            violations.append(f"field {key!r}={value!r} not in choices {enum}")
        if field.get("type") == "array" and isinstance(value, list):
            item_type = field.get("items")
            for elem in value:
                if item_type and _json_type(elem) != item_type and not (
                    item_type == "number" and _json_type(elem) == "integer"
                ):
                    violations.append(
                        f"field {key!r} array element {elem!r} is "
                        f"{_json_type(elem)}, contract requires {item_type}"
                    )
    return violations


def missing_required(method: str, endpoint: str, payload: dict) -> list[str]:
    """Required create fields absent from the payload (POST only)."""
    spec = contract_for(method, endpoint)
    keys = set(payload) | _CLIENT_INJECTED_KEYS
    return [f for f in spec.get("required", []) if f not in keys]


def capture_call(mock_make_request) -> tuple[str, str, dict]:
    """Extract (method, endpoint, data) from the mocked ``_make_request`` call."""
    assert mock_make_request.called, "_make_request was never called"
    args, kwargs = mock_make_request.call_args
    method = kwargs.get("method", args[0] if args else None)
    endpoint = kwargs.get("endpoint", args[1] if len(args) > 1 else None)
    data = kwargs.get("data", {})
    assert method and endpoint, f"could not parse call: args={args} kwargs={kwargs}"
    return method, endpoint, data or {}


def assert_payload_valid(mock_make_request, *, require_create: bool = False) -> None:
    """Assert the last ``_make_request`` payload matches the contract.

    Set ``require_create=True`` to also assert every create-required field is
    present (use for POST/create tools).
    """
    method, endpoint, data = capture_call(mock_make_request)
    problems = check_payload(method, endpoint, data)
    if require_create:
        missing = missing_required(method, endpoint, data)
        problems += [f"missing required-on-create field {f!r}" for f in missing]
    if problems:
        raise AssertionError(
            f"{method} {endpoint} payload violates the pfSense v2.10.0 contract:\n  "
            + "\n  ".join(problems)
        )
